database:
  user-name: toxa
  password: bernard94
  host: localhost
  port: 3306
  database-name: poker

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: toxa
    password: bernard94

logging:
  level:
    liquibase: INFO