server:
  port: 9002

database:
  user-name: toxa
  password: bernard94
  host: localhost
  port: 3306
  database-name: poker

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 9dQWEKLSTw

logging:
  level:
    liquibase: INFO