apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poker-user-app
  labels:
    k8s-app:  poker-user-app
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: poker-user-app
    spec:
      containers:
        - name: poker-user-app
          image: quay.io/kubernetes-ingress-controller/grpc-fortune-teller:0.1
          ports:
            - containerPort: 50051
              name: grpc