apiVersion: v1
kind: Service
metadata:
  name: poker-user-service
  namespace: default
spec:
  selector:
    k8s-app: poker-user-app
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc